facebook:
    client:
      clientId: 1407884669266237
      clientSecret: 8adff3eec13b6207cf8a5f3eeff09c4a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

google:
  client:
    clientId: 49028948097-abc28eprft8ricne642tpb3793mt3hj7.apps.googleusercontent.com
    clientSecret: -acbageOakeR9qJkKqZsxhAF
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo
